### ISSUE TITLE
froebell.com down

### ISSUE THREAD

**Issue by valentinbinotto** [Florianfro/FroebelsSite#1]
The connected webpage under the domain "froebell.com" is down. If you try to access it, it will respond with a 404 Error. Since the 404 page is from GitHub, I don't think there is a DNS error. There is a CNAME record for florianfro.github.io. under your domain. In the associated repository as well. Consequently, I do not believe in a DNS error. Did you perhaps select a different branch or source in the Github Pages settings?

![Bildschirmfoto vom 2023-01-08 16-48-16](https://user-images.githubusercontent.com/72608683/211205991-44c250c8-6d4f-4bfe-8ba9-319dd81dfc93.png)

**Comment by Florianfro** [comment]
Hello Valentin👋

I took it down intentionally until i get the Time to add my e-mail as a
Picture instead of Plain-Text.
I‘ve been sick the last Week so i wasn’t fit enough to do this but i‘ll try
to fix this soon.

Best Regards
Florian Fröbel

Valentin Binotto ***@***.***> schrieb am So. 8. Jan. 2023 um
16:50:

**Comment by valentinbinotto** [comment]
Hi Florian,

that's a great idea to avoid spam. In the past i made the mistake to publish my mail address as plain text and yeah.. that wasn't the best idea :). 
Alternatively to add a picture of your mail address, you could use this method (but i'm pretty sure you know what you're doing, so just an idea):


` <a href="mailto:user&commat;domain&period;com"> user&commat;domain&period;com</a>`

Just replace "user" with your name before the "@" and "domain" with your mail domain. For other methods to protect your mail, see [this](https://www.ionos.com/digitalguide/e-mail/e-mail-security/protecting-your-email-address-how-to-do-it/) page.

Have a nice day!
Vale
